### ISSUE TITLE
Move off of unsupported checksumdir dependency

### ISSUE THREAD

**Issue by matthewfeickert** [yadage/packtivity#109]
Find an alternative library to the `checksumdir` dependnecy

https://github.com/yadage/packtivity/blob/5029531e974436b15fc7b45bbac21f3aaf579bcb/setup.py#L17

which is unsupported (https://github.com/to-mc/checksumdir/issues/26) and causing issues in `recast-atlas` given use of `pkg_resources` (c.f. https://github.com/recast-hep/recast-atlas/issues/160).

**Comment by kratsg** [comment]
Use standalone code? Not clear that this is worthy of a dependency: https://stackoverflow.com/a/54477583

**Comment by matthewfeickert** [comment]
> Use standalone code? 

Maybe / Probably. It got added 7 years ago in  https://github.com/yadage/packtivity/commit/b7c760f5bdb0e608c251754a37fe8859164bb941 and I don't think has been reaexamined since then. It is also used only in one function

https://github.com/yadage/packtivity/blob/5029531e974436b15fc7b45bbac21f3aaf579bcb/packtivity/statecontexts/posixfs_context.py#L111-L128

**Comment by matthewfeickert** [comment]
Though, maybe https://github.com/andhus/dirhash-python instead given some of the points it makes and I'm lazy.
